services:
  - type: web
    name: anon-chat
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_VERSION
        value: 18.20.0
